"""add marketing_push_enabled to users

Revision ID: 21c007ba43e1
Revises: 2e2f89d86633
Create Date: 2026-09-18 13:35:34.647741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21c007ba43e1'
down_revision: Union[str, Sequence[str], None] = '2e2f89d86633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_records_id'), table_name='notification_records')
    op.drop_table('notification_records')
    op.add_column('users', sa.Column('marketing_push_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_push_enabled')
    op.create_table('notification_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('target_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('notification_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_records_id'), 'notification_records', ['id'], unique=False)
    # ### end Alembic commands ###
