"""add ghl_calendar_id to services

Revision ID: 363396b3bbe4
Revises: 8c454d2519c1
Create Date: 2026-08-21 12:04:40.967871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363396b3bbe4'
down_revision: Union[str, Sequence[str], None] = '8c454d2519c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('ghl_calendar_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'ghl_calendar_id')
    # ### end Alembic commands ###
