"""add bookings table

Revision ID: a76eb90d18b1
Revises: 45edd590fc0f
Create Date: 2026-08-23 01:37:58.535280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a76eb90d18b1'
down_revision: Union[str, Sequence[str], None] = '45edd590fc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('service_title', sa.String(length=255), nullable=False))
    op.add_column('bookings', sa.Column('service_icon', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('bookings_ibfk_1'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'service_id')
    op.drop_column('bookings', 'ghl_appointment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('ghl_appointment_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('bookings', sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('bookings_ibfk_1'), 'bookings', 'services', ['service_id'], ['id'])
    op.drop_column('bookings', 'service_icon')
    op.drop_column('bookings', 'service_title')
    # ### end Alembic commands ###
