"""add push_token to users table

Revision ID: f00e080a3c6a
Revises: a76eb90d18b1
Create Date: 2026-08-24 13:45:32.832252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00e080a3c6a'
down_revision: Union[str, Sequence[str], None] = 'a76eb90d18b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_token')
    # ### end Alembic commands ###
